### ISSUE TITLE
What would be needed to add support for other Levoit air purifiers?

### ISSUE THREAD

**Issue by andreklug** [acvigue/esphome-levoit-air-purifier#5]
Hi,

I've got the Levoit Vital 100S and 200S devices. I am very keen to use them with esphome.
I am more than happy to disassemble them and do some soldering. 

Could you please outline the steps that I would need to do in order to provide all information you'd need to add support for these devices as well?

Thank you!

**Comment by acvigue** [comment]
Hi @andreklug ! Please upload high resolution photos of the control board. It should have an ESP32 module or something similar.

**Comment by andreklug** [comment]
Here you go: 

Levoit Vital 100S, will disassemble the 200 next.

![Mittel (IMG_0300)](https://github.com/acvigue/esphome-levoit-air-purifier/assets/13343357/848a5bf5-fb47-4bb7-85c7-7875b75a7a76)
![Mittel (IMG_0301)](https://github.com/acvigue/esphome-levoit-air-purifier/assets/13343357/80ec54db-58a9-4350-bc8b-d7a6f17ab8ba)

**Comment by acvigue** [comment]
<img width="761" alt="Screenshot 2024-06-09 at 6 44 39 PM" src="https://github.com/acvigue/esphome-levoit-air-purifier/assets/34462061/2809d301-9195-4a37-96e9-5c6edf301313">


This board please

**Comment by andreklug** [comment]
oh that was stupid. Anyway, I am awake now:

![grafik](https://github.com/acvigue/esphome-levoit-air-purifier/assets/13343357/3df14fd7-8edd-481d-9b3f-7dc629a208cb)
![grafik](https://github.com/acvigue/esphome-levoit-air-purifier/assets/13343357/2d553218-6a79-420b-8598-6f7a0db9a3c4)
![grafik](https://github.com/acvigue/esphome-levoit-air-purifier/assets/13343357/52b3c7a5-a923-41a4-817d-c023e4fe83a0)

**Comment by andreklug** [comment]
a bit further information:

(to get this this into download mode, IO0 needs to be connected to ground when powering up / connecting to UART adapter)

This is how the device identifies itself:

```
esptool.py v4.7.0
Serial port /dev/cu.usbserial-0001
Connecting....
Detecting chip type... ESP32-C3
Chip is ESP32-C3 (QFN32) (revision v0.4)
Features: WiFi, BLE, Embedded Flash 4MB (XMC)
Crystal is 40MHz
```

I would now try your code as is to see if it already works. But as I have only been using esphome to flash precompiled stuff, I have no idea where to start compiling it. Would you mind giving me a short explaination?

Thank you!

**Comment by acvigue** [comment]
Sample config is given in repo - it will pull this code and compile for you

**Comment by andreklug** [comment]
Thank you. I created and adpated the config file. Deleted the flash and wrote it to the board. Setting the board to a generic ESP32-C3 compiles just fine, however the serial monitor shows "rst: 0x10 (RTCWDT_RTC_RST),boot:0xd (SPI_FLASH_BOOT) and then many lines of "invalid header: 0xffffffff".

```
I tried another C3 board and git this config error:

INFO ESPHome 2024.5.5
INFO Reading configuration /config/esphome/luftfilter-buro.yaml...
Failed config

uart: [source /config/esphome/luftfilter-buro.yaml:38]
  - 
    This pin cannot be used on ESP32-C3s and is already used by the SPI/PSRAM interface (function: SPIQ).
    tx_pin: GPIO17
    
    This pin cannot be used on ESP32-C3s and is already used by the SPI/PSRAM interface (function: SPID).
    rx_pin: GPIO16
    baud_rate: 115200

```

I guess the next step would be to identify the correct GPIO header. Any hint how to do this?

**Comment by acvigue** [comment]
Please upload full redacted with config

**Comment by andreklug** [comment]
In this very second I am trying the more generic "esp32dev" board. Here's the config:

```
esphome:
  name: "luftreiniger-buero"
  friendly_name: "Luftreiniger Büro"

esp32:
  board: esp32dev
  framework:
    type: esp-idf
    sdkconfig_options:
      CONFIG_FREERTOS_UNICORE: y

external_components:
  - source: github://acvigue/esphome-levoit-purifier
    components: [levoit]

logger:
  baud_rate: 115200

# Enable Home Assistant API
api:
  encryption:
    key: "REDACTED"

ota:
  password: "REDACTED"

wifi:
  networks:
    - ssid: !secret wifi_ssid_btst
      password: !secret wifi_password_btst

  ap:
    ssid: "LR-Buero Fallback"
    password: !secret ap_password

captive_portal:

uart:
  tx_pin: GPIO21
  rx_pin: GPIO20
  baud_rate: 115200

levoit:
  id: levoit1

fan:
  - platform: levoit
    name: Levoit Purifier

sensor:
  # Uptime sensor.
  - platform: uptime
    name: Uptime

  # WiFi Signal sensor.
  - platform: wifi_signal
    name: WiFi Signal
    update_interval: 60s

  # PM2.5 sensor
  - platform: levoit
    pm_2_5:
      name: PM2.5
    air_quality:
      name: Air Quality Index

switch:
  - platform: levoit
    display_lock:
      name: "Display Lock"
    display_on:
      name: "Display On"
    power:
      name: "Master Power"

select:
  - platform: levoit
    fan_mode:
      name: "Fan Mode"
    auto_mode:
      name: "Auto Mode"
```

**Comment by andreklug** [comment]
esp32dev as board results in the "invalid header" error.

**Comment by acvigue** [comment]
It should be the same board as the one I used c3 solo

**Comment by andreklug** [comment]
no luck... 

<img width="952" alt="grafik" src="https://github.com/acvigue/esphome-levoit-air-purifier/assets/13343357/2ddd3478-a569-4b2c-9815-580fe4574570">

**Comment by andreklug** [comment]
This is what I can select for C3:

<img width="312" alt="grafik" src="https://github.com/acvigue/esphome-levoit-air-purifier/assets/13343357/b2e55777-50c6-49fc-9b0d-07b38fe02337">

**Comment by andreklug** [comment]
So I tried esp32-c3-devkitc-02 (not found), devkitm1, m1i-kit. After a successful upload, both are returning this:

```
rst:0x10 (RTCWDT_RTC_RST),boot:0xd (SPI_FAST_FLASH_BOOT)
SPIWP:0xee
mode:QIO, clock div:1
load:0x3fcd5810,len:0x1684
ets_loader.c 78 
ESP-ROM:esp32c3-api1-20210207
Build:Feb  7 2021
```

**Comment by acvigue** [comment]
Do you have a dump of the original firmware

**Comment by andreklug** [comment]
yes, you want me to share it?

**Comment by acvigue** [comment]
yes

**Comment by andreklug** [comment]
[levoit.bin.zip](https://github.com/user-attachments/files/15794177/levoit.bin.zip)

**Comment by acvigue** [comment]
Please also upload the binary you are attempting to flash to the device. Since it contains encryption keys & such, you may email it to me if you'd like...

**Comment by acvigue** [comment]
```bash
~ ❯ esptool.py image_info Downloads/levoit.bin --version 2
esptool.py v4.7.0
File size: 4194304 (bytes)
Detected image type: ESP32-C3

ESP32-C3 image header
=====================
Image version: 1
Entry point: 0x403ce000
Segments: 3
Flash size: 4MB
Flash freq: 80m
Flash mode: DIO

ESP32-C3 extended image header
==============================
WP pin: 0xee (disabled)
Flash pins drive settings: clk_drv: 0x0, q_drv: 0x0, d_drv: 0x0, cs0_drv: 0x0, hd_drv: 0x0, wp_drv: 0x0
Chip ID: 5 (ESP32-C3)
Minimal chip revision: v0.0, (legacy min_rev = 3)
Maximal chip revision: v0.0

Segments information
====================
Segment   Length   Load addr   File offs  Memory types
-------  -------  ----------  ----------  ------------
      1  0x011c4  0x3fcd6100  0x00000018  DRAM, BYTE_ACCESSIBLE
      2  0x008a8  0x403ce000  0x000011e4  IRAM
      3  0x02ca0  0x403d0000  0x00001a94  IRAM

ESP32-C3 image footer
=====================
Checksum: 0x5d (valid)
Validation hash: db2ef7e43fbc89495281279dbd0ef193adca7a40ab28a34b67d3839f6113d226 (valid)
```

**Comment by SeveranExp** [comment]
@acvigue hey friend, are you still willing to work on this firmware?

**Comment by moimeme81** [comment]
> @acvigue hey friend, are you still willing to work on this firmware?
I was wondering the same. @andreklug anything new on your side?

**Comment by brcommander** [comment]
would be interested too

**Comment by andreklug** [comment]
Sorry for the late reply. I decided to go with the already supported 300 and 400 models for my home, as some other stuff took too much of my time.

**Comment by brcommander** [comment]
Oh I see...so I will have to go on myself. I managed to flash a custom esphome firmware and I see it in Home Assistant but neither the controls nor the sensors (pm 2.5...) are functional...

**Comment by brcommander** [comment]
so I got a kind of esphome firmware up, getting logs via wifi from esphome.
[19:57:35][C][levoit:066]: Levoit!
[19:57:39][VV][scheduler:225]: Running interval 'heartbeat' with interval=15000 last_execution=854217 (now=869233)
[19:57:39][V][levoit:019]: Sending heartbeat
[19:57:39][V][levoit:209]: Sending CMD (013140): A5.22.84.04.00.3E.01.31.40.00 (10)
[19:57:39][W][levoit:233]: ACK response timeout, retry #1
[19:57:39][V][levoit:209]: Sending CMD (013140): A5.22.85.04.00.3D.01.31.40.00 (10)
[19:57:39][W][levoit:233]: ACK response timeout, retry #2
[19:57:39][V][levoit:209]: Sending CMD (013140): A5.22.86.04.00.3C.01.31.40.00 (10)
[19:57:39][W][levoit:233]: ACK response timeout, retry #3
[19:57:39][V][levoit:209]: Sending CMD (013140): A5.22.87.04.00.3B.01.31.40.00 (10)
[19:57:39][W][levoit:233]: ACK response timeout, retry #4
[19:57:39][V][levoit:209]: Sending CMD (013140): A5.22.88.04.00.3A.01.31.40.00 (10)
[19:57:39][E][levoit:238]: Maximum NACKs received, skipping packet
[19:57:40][VV][scheduler:225]: Running interval 'status' with interval=5000 last_execution=865141 (now=870141)
[19:57:40][V][levoit:209]: Sending CMD (0129a1): A5.22.89.0A.00.DF.01.29.A1.00.01.7D.00.7D.00.00 (16)
[19:57:40][W][levoit:233]: ACK response timeout, retry #1
[19:57:40][V][levoit:209]: Sending CMD (0129a1): A5.22.8A.0A.00.DE.01.29.A1.00.01.7D.00.7D.00.00 (16)
[19:57:40][W][levoit:233]: ACK response timeout, retry #2
[19:57:40][V][levoit:209]: Sending CMD (0129a1): A5.22.8B.0A.00.DD.01.29.A1.00.01.7D.00.7D.00.00 (16)
[19:57:40][W][levoit:233]: ACK response timeout, retry #3
[19:57:40][V][levoit:209]: Sending CMD (0129a1): A5.22.8C.0A.00.DC.01.29.A1.00.01.7D.00.7D.00.00 (16)
[19:57:40][W][levoit:233]: ACK response timeout, retry #4
[19:57:40][V][levoit:209]: Sending CMD (0129a1): A5.22.8D.0A.00.DB.01.29.A1.00.01.7D.00.7D.00.00 (16)
[19:57:40][E][levoit:238]: Maximum NACKs received, skipping packet

@acvigue how did you find out the uart commands?

**Comment by brcommander** [comment]
ok thanks. Have to deal with usb-serial adapter and tools like screen etc. But I figured out that:
1. i had to change the esp config in my yaml:
```

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: esp-idf
    sdkconfig_options:
      CONFIG_PARTITION_TABLE_OFFSET: "0x9000"
      CONFIG_PARTITION_TABLE_CUSTOM_APP_BIN_OFFSET: "0x10000"
      CONFIG_PARTITION_TABLE_FILENAME: "partitions.csv"
```
[partitions.csv](https://github.com/user-attachments/files/18326458/partitions.csv)
2. GPIOs to be used in esphome config are: 18 (rx), 19 (tx)
3. sniffing von GPIO 19 (Testpoint 57) gave me some uart commands:
```
PowerON: A5 22 2C 07 00 B0 02 00 50 00 01 01 01
Fan Level 2: A5 22 2D 07 00 A6 02 03 55 00 01 01 02
Fan Level 1: A5 22 2E 07 00 A6 02 03 55 00 01 01 01
Fan Level 3: A5 22 2F 07 00 A3 02 03 55 00 01 01 03
Fan Level 1: A5 22 30 07 00 A4 02 03 55 00 01 01 01
Fan Level 4: A5 22 31 07 00 A0 02 03 55 00 01 01 04
PowerOFF: A5 22 33 07 00 AA 02 00 50 00 01 01 00
```
```
A5 12 F5 04 00 F8 02 00 55 00 
A5 12 F6 04 00 F7 02 00 55 00 
A5 12 F7 04 00 F6 02 00 55 00 
A5 12 F8 04 00 F5 02 00 55 00 
```
seem to be some kind of pings (every 3 seconds) / heartbeat / whatsoever


So I flashed esphome and got some log and at least there is communication:
[esphome.log](https://github.com/user-attachments/files/18326474/esphome.log)

The switches in HA for this device do not work and there are no data like pm2.5.
So I have to figure out which uart commands are used (beside the above mentioned)
